rootProject.name = "arqon-maestro"

include ":java-tree-sitter"
project(":java-tree-sitter").projectDir = file("tree-sitter/java-tree-sitter")

include ":client"
include ":code-engine"
include ":corpusgen"
include ":grammarflattener"
include ":speech-engine"
include ":offline"
include ":core"
include ":replayer"
include ":toolbelt"