plugins {
    id "com.google.protobuf" version "0.9.4"
}

dependencies {
    implementation "com.google.code.gson:gson:2.8.5"
    implementation "redis.clients:jedis:3.1.0"

    implementation rootProject.jettyServer
    implementation rootProject.jettyWebsocketServer
    implementation rootProject.websocketApi
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${rootProject.protobufVersion}"
    }
}

sourceSets {
    main {
        java {
            srcDirs "build/generated/source/proto/main/java"
        }
    }
}
